### PR TITLE
`explicit-length-check`: Check unsafe `LogicalExpression`s

### PR DESCRIPTION
**Pull request by fisker**

### CODE REVIEW

**Comment by fisker** [comment]
I think this will be the last PR for this rule. Some changes will help #887

**Comment by fisker** [comment]
Possible improvements in future:

1. Remove `>= 1` option, highly doubt someone prefer this.
2. Make it work for `Set#size`

**Comment by sindresorhus** [comment]
> Possible improvements in future:

Can you move this to an issue so we don't forget?

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Pull request merged**
