### PR TITLE
Add more projects to the integration test

### PR DESCRIPTION
**Pull request by fisker**
Add some new projects to tests
Add `vue-eslint-parser` tests
Remove `eslint-plugin-unicorn`, `yarn lint` already cover that.

Found 3 bugs during this, two fixed #560 #558 , one open #561

### CODE REVIEW

**Comment by fisker** [comment]
Any more projects want add?

**Comment by sindresorhus** [comment]
A few more:
- https://github.com/sindresorhus/create-dmg
- https://github.com/sindresorhus/cp-file
- https://github.com/sindresorhus/capture-website
- https://github.com/sindresorhus/file-type
- https://github.com/sindresorhus/slugify
- https://github.com/gatsbyjs/gatsby
- https://github.com/puppeteer/puppeteer
- https://github.com/zeit/next.js
- https://github.com/chakra-ui/chakra-ui
- https://github.com/ReactTraining/react-router
- https://github.com/facebook/relay
- https://github.com/mozilla/pdf.js

**Comment by sindresorhus** [comment]
The integration tests are failing now.

**Comment by fisker** [comment]
Yes, fixing

**Comment by fisker** [comment]
`relay` can't test, they are in `flow`. 

Now the integration tests take about 10 mins to complete, since we add some huge codebase.

**Comment by sindresorhus** [comment]
> Now the integration tests take about 10 mins to complete, since we add some huge codebase.

That's fine. Having some huge codebases is valuable. We can consider improving it with some caching in the future as we don't really need the latest commit, just something relatively recent.

**Comment by fisker** [comment]
I agree, that's why I want add more, but maybe we should only do `--fix-dry-run` test?

**Comment by sindresorhus** [comment]
> but maybe we should only do --fix-dry-run test?

Yes, definitely.

**Pull request merged**
