### PR TITLE
Use codecov instead of coveralls

### PR DESCRIPTION
**Pull request by fisker**
Use `coveralls` to report coverage.

### CODE REVIEW

**Comment by fisker** [comment]
@sindresorhus Can you setup `COVERALLS_REPO_TOKEN`?

**Comment by sindresorhus** [comment]
Done.

Why can we not use the action?

**Comment by fisker** [comment]
@sindresorhus Can't check on PR, https://github.com/sindresorhus/eslint-plugin-unicorn/pull/526#issuecomment-585086682

**Comment by fisker** [comment]
Are you sure your settings right?

https://github.com/sindresorhus/eslint-plugin-unicorn/pull/593/checks?check_run_id=500210367#step:6:5 should show 3 stars.

My fork:
https://github.com/fisker/eslint-plugin-unicorn/runs/500210380?check_suite_focus=true#step:6:5

image

**Comment by sindresorhus** [comment]
"Secrets", right?

Screenshot 2020-03-11 at 18 18 07

**Comment by fisker** [comment]
codecov seems works, but maybe need add repo to https://codecov.io/ to get the sresult

**Comment by sindresorhus** [comment]
Done

**Comment by fisker** [comment]
Seems works, just need update badge to merge, I'm AFK.

**Pull request merged**
