### PR TITLE
Support RegExp `v` flag

### PR DESCRIPTION
**Pull request by fisker**

### CODE REVIEW

**Comment by fisker** [comment]
Blocked by #2196

**Comment by fisker** [comment]
@novemberborn Sorry for bothering you. 

As you can see test is failing in this PR. We use a old version of ava https://github.com/sindresorhus/eslint-plugin-unicorn/blob/1629ebeb9d967f23245546aa2e0c2c182611ebb4/package.json#L71, we use it weird, we delete snapshots, and force ava to regenerate snapshots, to make sure snapshots won't change. https://github.com/sindresorhus/eslint-plugin-unicorn/blob/1629ebeb9d967f23245546aa2e0c2c182611ebb4/.github/workflows/main.yml#L40-L45

It works well until this PR. I already regenerate snapshots locally, but it still changes on CI. Maybe you known what possibly go wrong?

**Comment by novemberborn** [comment]
Looks like a test failed, it didn’t get to the diffing of the snapshots. And only in Node 20. Wouldn’t that be a real bug?

> we use it weird, we delete snapshots, and force ava to regenerate snapshots, to make sure snapshots won't change

That sounds like what AVA checks for in CI, what am I missing? Is this to handle differences between Node versions?

**Comment by fisker** [comment]
> Looks like a test failed, it didn’t get to the diffing of the snapshots. 

You are right.. I thought that's the "lint-test" job, which does the snapshot diff check, but it's not, really sorry.

> Wouldn’t that be a real bug?

Run test on Node.js v20 locally, tests all passed.
Run out of ideas...

**Comment by fisker** [comment]
Should be something wrong here https://github.com/sindresorhus/eslint-plugin-unicorn/blob/1629ebeb9d967f23245546aa2e0c2c182611ebb4/rules/prefer-regexp-test.js#L79-L92

I'll try to fix it later.

**Comment by fisker** [comment]
@novemberborn You are right, there is a bug indeed, thanks for your help.

**Pull request merged**
