### PR TITLE
`no-array-for-each`: Add more reasoning to the docs

### PR DESCRIPTION
**Pull request by Zamiell**
n/a

### CODE REVIEW

**Review by sindresorhus — APPROVED** [review]

**Comment by Zamiell** [comment]
how long do PRs usually sit after being approved but before being merged?

**Review by fisker — APPROVED** [review]

**Comment by cmdcolin** [comment]
random quip:  it would be cool to provide "examples" of what this text means e.g. a little code snippet showing the improved type narrowing, etc. as it's a little advanced (i'm just an onlooker of this repo)

**Comment by Zamiell** [comment]
The type narrowing difference is illustrated by the following code:

```ts
declare const foo: Foo | undefined;

if (foo === undefined) {
  return;
}

for (const element of array) {
  // type of `foo` is `Foo`
}
```

```ts
declare const foo: Foo | undefined;

if (foo === undefined) {
  return;
}

array.forEach((element) => {
  // type of `foo` is `Foo | undefined`
});
```

The variable mutation difference is illustrated by the following code:

```ts
function countArray(array: number[]) {
  let count = 0;

  for (const element of array) {
    count += element;
  }

  return count;
}
```

```ts
function countArray(array: number[]) {
  let count = 0;

  array.forEach((element) => {
    count += element;
  });

  return count; // lint error: count is never modified
}
```

**Comment by cmdcolin** [comment]
excellent, thanks for the demo!

**Pull request merged**
