### PR TITLE
Fix swapped rule descriptions

### PR DESCRIPTION
**Pull request by willheslam**

### CODE REVIEW

**Comment by sindresorhus** [comment]
That part of the readme is generated.

**Comment by willheslam** [comment]
> That part of the readme is generated.

Apologies, reading fail on my part! Will put together a proper fix soon...

**Comment by willheslam** [comment]
@sindresorhus Thanks for pointing that out - have now updated the source files as well as the readme.
Please let me know if I've missed anything!

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
