### PR TITLE
Update `ecmaVersion` to `2021`

### PR DESCRIPTION
**Pull request by fisker**

### CODE REVIEW

**Comment by fisker** [comment]
This requires #815

**Comment by sindresorhus** [comment]
There are some more places to update:

```
eslint-plugin-unicorn/index.js
13:				ecmaVersion: 2020,

eslint-plugin-unicorn/test/prefer-starts-ends-with.js
8:		ecmaVersion: 2020

eslint-plugin-unicorn/test/better-regex.js
7:		ecmaVersion: 2020

eslint-plugin-unicorn/test/prefer-node-remove.js
15:		ecmaVersion: 2020

eslint-plugin-unicorn/test/prefer-node-append.js
9:		ecmaVersion: 2020

eslint-plugin-unicorn/test/prefer-optional-catch-binding.js
11:		ecmaVersion: 2020

eslint-plugin-unicorn/test/no-for-loop.js
8:		ecmaVersion: 2020
14:		ecmaVersion: 5

eslint-plugin-unicorn/test/new-for-builtins.js
8:		ecmaVersion: 2020,

eslint-plugin-unicorn/test/no-null.js
12:		ecmaVersion: 2020,

eslint-plugin-unicorn/test/number-literal-case.js
11:		ecmaVersion: 2020

eslint-plugin-unicorn/test/no-fn-reference-in-iterator.js
27:		ecmaVersion: 2020

eslint-plugin-unicorn/test/prefer-spread.js
8:		ecmaVersion: 2020

eslint-plugin-unicorn/test/no-keyword-prefix.js
7:		ecmaVersion: 2020,
220:			parserOptions: {ecmaVersion: 6},
225:			parserOptions: {ecmaVersion: 6},

eslint-plugin-unicorn/test/no-reduce.js
13:		ecmaVersion: 2020

eslint-plugin-unicorn/test/import-style.js
10:		ecmaVersion: 2020
588:		ecmaVersion: 2020

eslint-plugin-unicorn/test/no-console-spaces.js
8:		ecmaVersion: 2020

eslint-plugin-unicorn/test/no-useless-undefined.js
11:		ecmaVersion: 2020
245:		ecmaVersion: 2020

eslint-plugin-unicorn/test/no-process-exit.js
8:		ecmaVersion: 2020,

eslint-plugin-unicorn/test/prefer-set-has.js
10:		ecmaVersion: 2020,

eslint-plugin-unicorn/test/prefer-array-find.js
17:		ecmaVersion: 2020,

eslint-plugin-unicorn/test/no-object-as-default-parameter.js
9:		ecmaVersion: 2020
175:		ecmaVersion: 2020

eslint-plugin-unicorn/test/prevent-abbreviations.js
14:		ecmaVersion: 5
23:		ecmaVersion: 2020,

eslint-plugin-unicorn/test/integration/config.js
14:		ecmaVersion: 2020,

eslint-plugin-unicorn/test/consistent-function-scoping.js
10:		ecmaVersion: 2020,
655:		ecmaVersion: 2020,

eslint-plugin-unicorn/test/throw-new-error.js
9:		ecmaVersion: 2020

eslint-plugin-unicorn/test/prefer-number-properties.js
32:		ecmaVersion: 2020

eslint-plugin-unicorn/test/catch-error-name.js
10:		ecmaVersion: 2020
```

**Comment by fisker** [comment]
I think they don't have to use the latest?

**Comment by sindresorhus** [comment]
Maybe not always, but it's sometimes hard to see when it could have been useful. And it's annoying to have to individually judge every time it updates. Wouldn't it be easier if everything was the same? We could maybe define a shared constants and import it into every test. Or better yet, some kind of custom test helper, like https://github.com/sindresorhus/eslint-plugin-unicorn/pull/554

**Comment by fisker** [comment]
I'll work on #554 when I have time.

**Comment by fisker** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/2468

**Pull request merged**
