### PR TITLE
Increase width of readme rules table name column (with HTML table)

### PR DESCRIPTION
**Pull request by bmish**
Alternative to #1197.

### CODE REVIEW

**Comment by bmish** [comment]
It looks like this doesn't help us because github markdown strips the style tag from `<td style="white-space: nowrap">`.

**Comment by fisker** [comment]
Does `<td width="150">` work?

**Comment by fisker** [comment]
Or [`<col>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col)

**Comment by bmish** [comment]
> Does `<td width="150">` work?

Looks like `<td width="250">` works and is a good width.

**Comment by bmish** [comment]
@fisker markdown doesn't work inside HTML, mainly affecting our backtick code samples in the rule descriptions which no longer render.

Looks like I'd have to manually replace the backticks with `<code>` to fix it, or ideally find a markdown-to-HTML converter which could handle any other markdown (bold, italics) that happened to be used in rule descriptions.

**Comment by fisker** [comment]
Lets move it to the first `<th>`, should work too.

**Comment by fisker** [comment]
Try wrap descriptions with `<span>`, should work.

**Comment by fisker** [comment]
Or `markdown="1"`, found here https://stackoverflow.com/questions/29368902/how-can-i-wrap-my-markdown-in-an-html-div

**Comment by fisker** [comment]
Haha, out of ideas.

**Comment by bmish** [comment]
@fisker the markdown renders correctly when the rule description is separated by blank lines.

**Comment by fisker** [comment]
Let's use markdown for link too? And align code with `outdent`.

**Comment by fisker** [comment]
I wonder if this file can be rendered correctly on npmjs.com.

**Comment by bmish** [comment]
> I wonder if this file can be rendered correctly on npmjs.com.

Good question. That's one reason why I would slightly prefer avoiding the custom HTML solution and going with #1197 instead.

**Comment by fisker** [comment]
I don't have strong opinion. But worth to try, learned 😄

**Comment by fisker** [comment]
Found another solution https://stackoverflow.com/questions/36121672/set-table-column-width-via-markdown/51701842

**Comment by bmish** [comment]
> Found another solution https://stackoverflow.com/questions/36121672/set-table-column-width-via-markdown/51701842, adding `&nbsp;` seems nice.

I tried those solutions earlier and didn't have luck with them.

**Comment by bmish** [comment]
Shall we make a call on going with this PR or #1197 before I keep fixing this PR?

**Comment by fisker** [comment]
> I tried those solutions earlier and didn't have luck with them.

The `&nbsp;` trick works https://github.com/fisker/eslint-plugin-unicorn/tree/readme-rule-name-size#rules

**Comment by fisker** [comment]
`&emsp;` work too

**Comment by bmish** [comment]
> > I tried those solutions earlier and didn't have luck with them.
> 
> The `&nbsp;` trick works https://github.com/fisker/eslint-plugin-unicorn/tree/readme-rule-name-size#rules

Oh nice! That's a bit different from what I tried. Want to just open a PR with your change and I'll close mine?

**Pull request closed without merging**
