### PR TITLE
Update `regex-shorthand` to ignore regex with `u` flag

### LINKED ISSUE #447: regex-shorthand suggesting invalid regular expression
I have this error
```
error  /(\s|\.|@|_|-)/u can be optimized to /([\s-.@_])/u  unicorn/regex-shorthand
```

But the regex `/([\s-.@_])/u` is invalid, as it is trying to say a range between `\s` and `.` (`\s-.`).

If I manually change it to `/[\s.@_-]/u`, which is correct, I get:
```
error  /[\s.@_-]/u can be optimized to /[\s-.@_]/u  unicorn/regex-shorthand
```

My change is correct, as `-` at the end of a match group means literally `-`. But the optimization suggestion is wrong because it means a range.

I had had these problems with eslint-plugin-unicorn version 14.0.0

### LINKED ISSUE #448: (v14): false-positive "Invalid regular expression: Invalid character class"
Hi! I noticed a bug in the latest release with some regular expressions, as this one:

```typescript
/^test-(?<name>[a-zA-Z-\d]+)$/u
```

It makes ESLint crash (not report an error, actually crash).

### PR DESCRIPTION
**Pull request by fisker**
`regexp-tree` might optimize RegExp to invalid codes, crash ESLint

fixes: #446
fixes #447 
fixes #448

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is a good temporary workaround, but we should find the actual cause for this and get it fixed.

> regexp-tree might optimize RegExp to invalid codes

Can you open an issue on `regexp-tree` about that?

**Comment by fisker** [comment]
turns out this also fixes #448, adding more test

**Comment by fisker** [comment]
@sindresorhus these might related, not confirmed yet

https://github.com/DmitrySoshnikov/regexp-tree/issues/162
https://github.com/BrainMaestro/eslint-plugin-optimize-regex/issues/23

**Comment by sindresorhus** [comment]
Does this also fix https://github.com/sindresorhus/eslint-plugin-unicorn/issues/447 ? Can you add a test for it?

**Comment by fisker** [comment]
> Does this also fix #447 ? Can you add a test for it?

No, this doesn't, different case. If I find anything will do another PR.

**Comment by fisker** [comment]
one second

**Comment by fisker** [comment]
Yes, this fixes #447, I think he didn't use `--fix`, so only suggest the wrong code, but not crash ESLint

**Comment by fisker** [comment]
Add tests, we should do a path release

**Comment by fisker** [comment]
@sindresorhus this `.toRegExp()` might not safe, maybe we should skip the `u` flag?

**Comment by fisker** [comment]
close in favor of #454

**Pull request closed without merging**
