### PR TITLE
Update `ESLint` to v7

### LINKED ISSUE #368: The `ruldeId` property in tests is not correctly enforced
See: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/296#discussion_r324564372

### PR DESCRIPTION
**Pull request by fisker**
Prepare for ESLint 7

Closes #368

### CODE REVIEW

**Comment by fisker** [comment]
```text
 AssertionError {
    actual: false,
    code: 'ERR_ASSERTION',
    expected: true,
    generatedMessage: false,
    operator: '==',
    message: 'Invalid error property name \'ruleId\'. Expected one of [\'message\', \'messageId\', \'data\', \'type\', \'line\', \'column\', \'endLine\', \'endColumn\', \'suggestions\'].',
  }
```

This is a breaking change https://github.com/eslint/eslint/pull/12096

**Comment by sindresorhus** [comment]
I guess we should use `messageId` instead?

**Comment by fisker** [comment]
I use `messageId` and `data` for few rules in my recent PRs, but I feel it's not safe, so I add extra tests in this PR https://github.com/sindresorhus/eslint-plugin-unicorn/pull/666/files#diff-01ad3bc5b5ffd5a28466a36319461266R209

**Comment by fisker** [comment]
Updating to v7.0.0

**Comment by brettz9** [comment]
Could we get a new release including this commit?

When using ESLint 7, I'm getting an error blocking reporting of all other linting errors:

> context.report() called with a messageId of 'unexpectedComment' which is not present in the 'messages' config

I note that this `unexpectedComment` message is not present in eslint-plugin-unicorn but is present in the `no-warning-comments` rule from ESLint 7 which the `expiring-todo-comments` rule requires. I think this PR should have fixed the issue, but was wondering if we could get a new release. Thanks!

**Comment by fisker** [comment]
@brettz9 
This error already fixed in  https://github.com/sindresorhus/eslint-plugin-unicorn/pull/668 v19.0.0 should include that code.

**Comment by brettz9** [comment]
Ugh, apologies for the wasted time. No, I need to adjust, thank you!!

**Comment by fisker** [comment]
No need apologies, glad I did that before ESLint 7 release.

**Pull request merged**
