### PR TITLE
Fix the `expiring-todo-comments` rule for programmatic usage of ESLint

### LINKED ISSUE #373: `expiring-todo-comments` breaks `eslint --print-config` in dirs with no `package.json`
If `eslint --print-config` is run in a dir with no `package.json`, then the `expiring-todo-comments` rule throws an error. So the `--print-config` command doesn't work with this rule, at the moment.

```
$ eslint --print-config src/index.js

Error: ENOENT: no such file or directory, open 'src/package.json'
Referenced from: .eslintrc.js
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:350:35)
    at AsyncFunction.module.exports.sync (/usr/local/lib/node_modules/eslint-plugin-unicorn/node_modules/read-pkg/index.js:34:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:20:21)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
```

### PR DESCRIPTION
**Pull request by lubien**
Supports running eslint 5 on deeper folders properly.

I can't quite make integration tests work on my machine ('Unknown system error -254') so I'll trouble the CI a little if you don't mind.

Fixes #373

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Supports running eslint 5 on deeper folders properly.

Do you mean ESLint **6**? Because we don't support ESLint 5 anymore.

**Comment by lubien** [comment]
> Do you mean ESLint **6**? 

No, 5, actually.

> Because we don't support ESLint 5 anymore.

Oh.

Giving the highlights of the issue: `eslint --print-config` when CWD is a deeper folder such as `src` works fine on 6 but fails to find package.json on 5.

So we should close this then?

**Comment by sindresorhus** [comment]
> So we should close this then?

No, I can actually reproduce the issue in ESLint 6 when using the programmatic API. Just tried upgrading XO to the latest version of this now.

```
cli-main › fix option

  /Users/sindresorhus/dev/oss/xo/test/node_modules/eslint-plugin-unicorn/node_modules/read-pkg/index.js:34

  Rejected promise returned by test. Reason:

  Error {
    cmd: '/Users/sindresorhus/dev/oss/xo/cli-main.js --fix /private/var/folders/3x/jf5977fn79jbglr7rk0tq4d00000gn/T/f2a04c7a-1776-4d7b-abae-f0eaee37f5f7/x.js',
    code: 1,
    failed: true,
    killed: false,
    signal: null,
    stderr: `Error: Failed to load plugin 'unicorn' declared in 'BaseConfig » /Users/sindresorhus/dev/oss/xo/config/plugins.js': ENOENT: no such file or directory, open '/Users/sindresorhus/dev/oss/xo/test/package.json'␊
    Referenced from: /Users/sindresorhus/dev/oss/xo/config/plugins.js␊
        at Object.openSync (fs.js:443:3)␊
        at Object.readFileSync (fs.js:343:35)␊
        at AsyncFunction.module.exports.sync.options [as sync] (/Users/sindresorhus/dev/oss/xo/node_modules/eslint-plugin-unicorn/node_modules/read-pkg/index.js:34:28)␊
        at Object.<anonymous> (/Users/sindresorhus/dev/oss/xo/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:20:21)␊
        at Module._compile (internal/modules/cjs/loader.js:778:30)␊
        at Module.replacementCompile (/Users/sindresorhus/dev/oss/xo/node_modules/append-transform/index.js:58:13)␊
        at Module._extensions..js (internal/modules/cjs/loader.js:789:10)␊
        at Object.<anonymous> (/Users/sindresorhus/dev/oss/xo/node_modules/append-transform/index.js:62:4)␊
        at Module.load (internal/modules/cjs/loader.js:653:32)␊
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)␊
    `,
    stdout: '',
    timedOut: false,
    message: `Command failed: /Users/sindresorhus/dev/oss/xo/cli-main.js --fix /private/var/folders/3x/jf5977fn79jbglr7rk0tq4d00000gn/T/f2a04c7a-1776-4d7b-abae-f0eaee37f5f7/x.js␊
    Error: Failed to load plugin 'unicorn' declared in 'BaseConfig » /Users/sindresorhus/dev/oss/xo/config/plugins.js': ENOENT: no such file or directory, open '/Users/sindresorhus/dev/oss/xo/test/package.json'␊
    Referenced from: /Users/sindresorhus/dev/oss/xo/config/plugins.js␊
        at Object.openSync (fs.js:443:3)␊
        at Object.readFileSync (fs.js:343:35)␊
        at AsyncFunction.module.exports.sync.options [as sync] (/Users/sindresorhus/dev/oss/xo/node_modules/eslint-plugin-unicorn/node_modules/read-pkg/index.js:34:28)␊
        at Object.<anonymous> (/Users/sindresorhus/dev/oss/xo/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:20:21)␊
        at Module._compile (internal/modules/cjs/loader.js:778:30)␊
        at Module.replacementCompile (/Users/sindresorhus/dev/oss/xo/node_modules/append-transform/index.js:58:13)␊
        at Module._extensions..js (internal/modules/cjs/loader.js:789:10)␊
        at Object.<anonymous> (/Users/sindresorhus/dev/oss/xo/node_modules/append-transform/index.js:62:4)␊
        at Module.load (internal/modules/cjs/loader.js:653:32)␊
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)␊
    ␊
    `,
  }

  AsyncFunction.module.exports.sync.options [as sync] (node_modules/eslint-plugin-unicorn/node_modules/read-pkg/index.js:34:28)
  Object.<anonymous> (node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:20:21)
  makeError (node_modules/execa/index.js:174:9)
  Promise.all.then.arr (node_modules/execa/index.js:278:16)
```

**Comment by lubien** [comment]
> No, I can actually reproduce the issue in ESLint 6 when using the programmatic API. Just tried upgrading XO to the latest version of this now.

I'll try when I get home. Perhaps using read-pkg-up will also work around this.

> Do you mean ESLint 6?

Also should redo the commit description?

**Comment by sindresorhus** [comment]
> Also should redo the commit description?

Nah, I'll squash when merging anyway.

**Comment by lubien** [comment]
> No, I can actually reproduce the issue in ESLint 6 when using the programmatic API. 

<details>
<summary>
Tested with this code.
</summary>

```
const { CLIEngine } = require("eslint")
const cli = new CLIEngine();

const report = cli.executeOnFiles(["index.js"]);
console.log(report)
```

</details>

Works now with this last commit in my npm link setup.

**Pull request merged**
