### PR TITLE
Make `regex-shorthand` rule use `regexp-tree` for regex literals

### LINKED ISSUE #157: The `regex-shorthand` rule has a false-negative
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/eslint-plugin-unicorn/issues/157)

This doesn't cause a lint error:

```js
const foo = /^by @([a-zA-Z0-9-]+)/
```

Even though it could be:

```js
const foo = /^by @([a-zA-Z\d-]+)/
```

I think we might need to use some more advanced detection. Maybe [`regexp-tree`](https://github.com/DmitrySoshnikov/regexp-tree). Although, it has an [optimizer](https://github.com/DmitrySoshnikov/regexp-tree#using-optimizer-api) API already, which I think already handles this and many other cases.

// @SamVerschueren

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $30.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($30.00)

### Submitted pull Requests
- [#261 regex-shorthand: new option to fix #157](https://issuehunt.io/r/sindresorhus/eslint-plugin-unicorn/pull/261)
- [#437 update  to use  for regex literals](https://issuehunt.io/r/sindresorhus/eslint-plugin-unicorn/pull/437)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/eslint-plugin-unicorn/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by jdanil**
Continuing on from #261 to fix #157.

- Updated to use `regexp-tree` to optimize for more cases.
- Updated error messages to include more detailed information.
- Fixed `regex-shorthand` code errors in `eslint-plugin-unicorn`.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#157: The `regex-shorthand` rule has a false-negative](https://issuehunt.io/repos/55832243/issues/157)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by fisker** [comment]
wow, so many regexp in codebase can be optimized

**Comment by fisker** [comment]
looks the same as https://github.com/BrainMaestro/eslint-plugin-optimize-regex/blob/master/lib/rules/optimize-regex.js to me

**Comment by jdanil** [comment]
> wow, so many regexp in codebase can be optimized

Yah a couple. Most of the changes are re-ordering though.

> looks the same as https://github.com/BrainMaestro/eslint-plugin-optimize-regex/blob/master/lib/rules/optimize-regex.js to me

Yep. That's what #261 was based off of too. But just for regex literals. `RegExp` with string arguments is still using `clean-regexp`.

**Comment by fisker** [comment]
@jdanil off-topic , how did you fix those `RegExp`s? I'm not sure `yarn lint` error message is clear enough

**Comment by jdanil** [comment]
> @jdanil off topic , how did you fix those `RegExp`s? I'm not sure `yarn lint` error message is clear enough

I used the optimised regex from `regexp-tree`. The only problem I had with some of the optimised regex was that `regexp-tree` tries to order groups alphabetically I think. It would have symbols followed by alphanumeric characters, so some of the symbols needed to be escaped.

**Comment by fisker** [comment]
@jdanil I mean did you fix them by `npm run integration --fix` or ?

**Comment by jdanil** [comment]
> @jdanil I mean did you fix them by `npm run lint --fix` or ?
> 
> I put a message here, https://travis-ci.org/sindresorhus/eslint-plugin-unicorn/jobs/612730929#L266
> 
> But not sure is it clear

Ohh. No I missed that script and comment.
I was actually surprised to see the updated rule running on the PR in travis!
I just updated all the issues it reported because I didn't know I could run the autofix.
Thanks for pointing it out 🙂

**Comment by fisker** [comment]
@jdanil thanks for your feedback.

**Pull request merged**
