### PR TITLE
Replace nyc with c8

### PR DESCRIPTION
**Pull request by XhmikosR**
https://packagephobia.com/result?p=nyc%2Cc8

### CODE REVIEW

**Comment by fisker** [comment]
https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1608#issuecomment-966782691

**Comment by XhmikosR** [comment]
Oh, I wasn't aware of that. Let's close it then and someone else can switch it later.

**Comment by XhmikosR** [comment]
Is it such a big deal, though? I still think it's worth it but I'll leave it to you @fisker @sindresorhus to decide.

Feel free to close it yourselves :)

**Comment by fisker** [comment]
Can you replace `istanbul ignore` with `c8 ignore`?

**Comment by XhmikosR** [comment]
I pushed a patch to replace istanbul with c8, but unsure how it'll handle topics...

**Comment by fisker** [comment]
You should move the ignore reason out https://github.com/istanbuljs/v8-to-istanbul/blob/6c2e2ecd2aece8b01543f75dfa203744f8a785b9/lib/source.js#L54

**Comment by XhmikosR** [comment]
I don't think `ignore next` ignores the next block, so the statements are not equivalent. It just ignores the next line. The workaround is to specify the lines to ignore...

**Comment by fisker** [comment]
There are `ignore start` and `ignore end` we can use.

**Comment by XhmikosR** [comment]
In most cases it should be fine doing `c8 ignore next 3` and it's shorter. Are you OK with this?

**Comment by fisker** [comment]
Yes.

**Comment by XhmikosR** [comment]
All right, this is as good as it gets from my side :)

Feel free to tweak it further if needed.

**Review by fisker — APPROVED** [review]
LGTM, Thank You!

**Pull request merged**
