### PR TITLE
Refactor: replace `isSameNode` with `hasSameRange`

### PR DESCRIPTION
**Pull request by fisker**
`Node`s has same range didn't mean they are the same node,

example

```
a
```

Both `Program`, `ExpressionStatement`, `Identifier` have same range `[0, 1]`.

Add `hasSameRange` to use it detect shorthands

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you reopen the issue in the main Babel repo? Per https://github.com/babel/babel-eslint/issues/809#issuecomment-668300104

**Comment by fisker** [comment]
I'll confirm this bug still exits first, but it doesn't matter, because `babel-eslint` will have this bug forever...

**Comment by sindresorhus** [comment]
> but it doesn't matter, because babel-eslint will have this bug forever...

Sure, but at some point (sooner than later), we'll remove support for `babel-eslint` and require users to use `@babel/eslint-parser`.

**Comment by fisker** [comment]
I've confirmed, this is fixed in `@babel/eslint-parser`

**Pull request merged**
