### PR TITLE
Fix integration test

### PR DESCRIPTION
**Pull request by fisker**
Ref: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/912#issuecomment-738660182

### CODE REVIEW

**Comment by fisker** [comment]
Strange, local test catch that error, but not on CI...

**Comment by fisker** [comment]
Ah, [error is here](https://github.com/sindresorhus/eslint-plugin-unicorn/pull/914/checks?check_run_id=1497816806#step:5:333), didn't fail

**Comment by fisker** [comment]
Got the error, https://github.com/sindresorhus/eslint-plugin-unicorn/runs/1498259018#step:5:438, but found other problems.

**Comment by sindresorhus** [comment]
I merged in `master`, but still failing.

**Comment by fisker** [comment]
Need fix #915 first https://github.com/sindresorhus/eslint-plugin-unicorn/runs/1508474215#step:5:367, I'll take care of this.

**Comment by fisker** [comment]
This is strange https://github.com/sindresorhus/eslint-plugin-unicorn/pull/914/checks?check_run_id=1510136698#step:5:339, I can't reproduce locally.

**Pull request merged**
