### PR TITLE
Do not warn if `.flat()` has more than one parameter or if the one parameter is not `1`

### LINKED ISSUE #315: `prefer-flat-map` fixer bug
`Array#flat` accepts argument `depth`, but flatMap not.

The fixer is not considering this `depth`, codes like

```js
const foo = [[1]].map(i => [i]).flat(2)
```

should not be reported.

### PR DESCRIPTION
**Pull request by MrHen**
Fixes #315.

A follow up question is if we should warn / fix on `.flat(1)` which is default flattening behavior but I wanted to get the fix out quickly.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Yes, we should report and fix `.flat(1)`.

**Comment by fisker** [comment]
and also `undefined` ? maybe also `"1"`? 

according to , https://tc39.github.io/proposal-flatMap/#sec-Array.prototype.flat 

Any value can `ToInteger` equals to 1, all the same

**Comment by sindresorhus** [comment]
@fisker Nah. No one would actually pass in that. Not worth caring about.

**Comment by fisker** [comment]
make sense

**Comment by fisker** [comment]
on second thought,  most people also not pass `1`, how about not check arguments at all, instead a new rule to check `flat` argument ?

**Comment by sindresorhus** [comment]
> on second thought, most people also not pass 1, how about not check arguments at all, instead maybe make a new rule to check flat argument ?

A rule that checks arguments for built-ins in general sounds useful, but would be very fragile without type information. Better to just use TypeScript then.

**Pull request merged**
