### PR TITLE
Rename rules

### LINKED ISSUE #945: Rename `no-fn-reference-in-iterator`
`fn` is [abbreviation listed in `prevent-abbreviations`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/83a64538bc1662c4bac9822263d8ec008c6dfee5/rules/prevent-abbreviations.js#L109-L111), we should avoid use it ourself

Suggestions:

- `no-array-iterator-reference`
- `no-array-callback-reference` [MDN use `callback` term in all their docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Parameters), and [the spec uses `callbackfn`](https://www.ecma-international.org/ecma-262/11.0/index.html#sec-array.prototype.map)

### PR DESCRIPTION
**Pull request by fisker**
- `no-fn-reference-in-iterator` -> `no-array-callback-reference`
- `no-array-instanceof` -> `no-instanceof-array`
- `no-reduce` -> `no-array-reduce`
- `prefer-dataset` -> `prefer-dom-node-dataset`
- `prefer-flat-map` -> `prefer-array-flat-map`
- `prefer-replace-all` -> `prefer-string-replace-all`
- `prefer-starts-ends-with` -> `prefer-string-starts-ends-with`
- `prefer-text-content` -> `prefer-dom-node-text-content`
- `prefer-trim-start-end` -> `prefer-string-trim-start-end`
- `prefer-event-key` -> `prefer-keyboard-event-key`
- `prefer-node-append` -> `prefer-dom-node-append`
- `prefer-node-remove` -> `prefer-dom-node-remove`

Fixes #945

### CODE REVIEW

**Comment by fisker** [comment]
`dataset` is provide by [`HTMLOrForeignElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset), is it okay to name `prefer-node-dataset`?

**Comment by sindresorhus** [comment]
> dataset is provide by HTMLOrForeignElement, is it okay to name prefer-node-dataset?

Sure, `HTMLElement` inherits from `Node`.

> prefer-event-key to prefer-keyboard-event-key, KeyboardEvent.key?

👍

**Comment by fisker** [comment]
As we are renaming batch of rule names, can you go over all rule names, check if any other rule need rename, so we can do it in one PR.

**Comment by sindresorhus** [comment]
Maybe `prefer-negative-index` => `prefer-negative-index-in-slice` / `prefer-slice-negative-index`, but not sure it's worth renaming just for that.

**Comment by fisker** [comment]
It also work for `.splice`, I think we should keep it.

**Comment by sindresorhus** [comment]
Oh right. I missed the `p`. Then I think your list is good.

**Comment by fisker** [comment]
Thanks for updating the documentation!

**Comment by futpib** [comment]
> - `prefer-dataset` -> `prefer-node-dataset`
> - `prefer-text-content` -> `prefer-node-text-content`

Wouldn't `dom-node` be less ambiguous as `node` can mean Node.js?

- `prefer-dataset` -> `prefer-dom-node-dataset`
- `prefer-text-content` -> `prefer-dom-node-text-content`

**Comment by fisker** [comment]
I use `node` because we already have `prefer-node-append` and `prefer-node-remove`.

I don't have strong opinion, but if we are doing this, these two need rename too.

To be honest, I really don't know what `prefer-text-content` for, when I first saw this rule.

**Comment by sindresorhus** [comment]
I agree, `dom-node` is better.

**Comment by fisker** [comment]
`prefer-query-selector` -> `prefer-dom-query-selector` too?

**Comment by sindresorhus** [comment]
> prefer-query-selector -> prefer-dom-query-selector too?

Nah. There's no confusion there.

**Pull request merged**
