### PR TITLE
Add `switch-braces` rule

### LINKED ISSUE #1702: Rule proposal: Switch braces
### Description

See https://github.com/xojs/xo/issues/650 for additional context.

### Fail

```js
switch (value) {
		case 'unicorn':
			break;
}
```

### Pass

```js
switch (value) {
		case 'unicorn': {
			break;
		}
}
```

### PR DESCRIPTION
**Pull request by Richienb**
Fixes #1702

### CODE REVIEW

**Comment by Richienb** [comment]
The fixer will require some tweaks to get it working nicer with both multiline and single-line expressions. Also some more tests may help.

**Comment by Richienb** [comment]
`no-array-for-each` and `no-useless-spread` are both triggering the rule so that parts seems to work

**Comment by fisker** [comment]
You may misunderstood, the braces creates a new scope, when there are variable declare, braces are required. Correct me if I'm wrong.

**Comment by Richienb** [comment]
Yes, you are correct. The way [MDN describes it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch#block-scope_variables_within_switch_statements) makes it sound like more of an inconvenience but this will probably make automatic fixing improbable.

**Comment by fisker** [comment]
My personal opinion, we should only report those cases that braces can be removed.

**Comment by Richienb** [comment]
Stylistically speaking, we'd only want for all blocks to either have braces or blocks.

**Comment by sindresorhus** [comment]
I personally think braces should always be used for consistency and safety.

**Comment by Richienb** [comment]
The rule is built to allow for either always braces (default) or never braces to allow for differing opinions. The whole context thing adds extra steps to take into account variables defined outside of break statements which would throw a runtime error which makes fixing it a manual thing.

**Comment by sindresorhus** [comment]
@Richienb Still interested in finishing this?

**Pull request closed without merging**
