### PR TITLE
Add `no-invalid-fetch-options` rule

### LINKED ISSUE #1989: Rule proposal: force `method: "POST"` on fetch calls with body
### Description

I sometimes forget to add `method: 'POST'` to fetch calls

image

### Fail

```js
fetch('http://example.com', { body: '{}' })
```

### Pass

```js
fetch('http://example.com', { method: 'POST', body: '{}' })
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by fisker**
Fixes #1989

### CODE REVIEW

**Comment by silverwind** [comment]
Should add [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS):

> Request has body 	No

**Comment by fisker** [comment]
These doesn't thows

```
fetch('/', {method: 'OPTIONS', body: 'foo'})
fetch('/', {method: 'TRACE', body: 'foo'})
fetch('/', {method: 'CONNECT', body: 'foo'})
```

**Comment by silverwind** [comment]
> These doesn't thows
> 
> ```
> fetch('/', {method: 'OPTIONS', body: 'foo'})
> fetch('/', {method: 'TRACE', body: 'foo'})
> fetch('/', {method: 'CONNECT', body: 'foo'})
> ```
> 
> The spec only forbids `GET` and `HEAD`.

Ok, then MDN is just inaccurate.

**Comment by GauBen** [comment]
Thanks @fisker!

**Pull request merged**
