### PR TITLE
Improve `no-hex-escape` coverage

### PR DESCRIPTION
**Pull request by fisker**

### CODE REVIEW

**Comment by fisker** [comment]
There is no coverage reported on PR, I've tried to change the actions config file, but no luck.

**Comment by sindresorhus** [comment]
https://github.com/coverallsapp/github-action/issues/7

**Comment by fisker** [comment]
But i got the coverage result

image


https://github.com/fisker/get-text-nodes/pull/258

With same command

https://github.com/fisker/get-text-nodes/blob/master/.github/workflows/continuous-integration.yml#L52-L57

**Comment by fisker** [comment]
Is there any setting on coveralls.io

**Pull request merged**
