### PR TITLE
prefer-trim-start-end: Fix error message, improve report location

### PR DESCRIPTION
**Pull request by zawys**

### CODE REVIEW

**Review by sindresorhus — APPROVED** [review]

**Comment by sindresorhus** [comment]
The fact that no test needed updating for this is a good indicator this rule needs some more tests.

**Comment by zawys** [comment]
Are you about to add a test?

**Comment by zawys** [comment]
Ok, I fixed the tests.

**Comment by zawys** [comment]
That should be a temporary failure. Could you please restart the checks?

**Review by fisker — APPROVED** [review]

**Review by fisker — APPROVED** [review]

**Pull request merged**
