### PR TITLE
Allow back slashes - fixes #85

### LINKED ISSUE #85: escape-case and no-hex-escape false positives – need to handle backslashes
package.json:

```json
{
  "private": true,
  "eslintConfig": {
    "env": {
      "es6": true
    },
    "parserOptions": {
      "ecmaVersion": 2017,
      "sourceType": "module"
    },
    "plugins": [
      "unicorn"
    ],
    "rules": {
      "unicorn/escape-case": "error",
      "unicorn/no-hex-escape": "error"
    }
  },
  "scripts": {
    "test": "eslint test.js"
  },
  "devDependencies": {
    "eslint": "^3.15.0",
    "eslint-plugin-unicorn": "^2.0.1"
  }
}
```

test.js:

```js
"\\ufeff"
"\\\\xa0"
```

Output:

```
$ npm test

> @ test /home/lydell/bugs/eslint-plugin-unicorn-bugs
> eslint test.js


/home/lydell/bugs/eslint-plugin-unicorn-bugs/test.js
  1:1  error  Use uppercase characters for the value of the escape sequence  unicorn/escape-case
  2:1  error  Use uppercase characters for the value of the escape sequence  unicorn/escape-case
  2:1  error  Use unicode escapes instead of hexadecimal escapes             unicorn/no-hex-escape

✖ 3 problems (3 errors, 0 warnings)

npm ERR! Test failed.  See above for more details.
```

Expected: No errors.

### PR DESCRIPTION
**Pull request by matijs**

### CODE REVIEW

**Comment by sindresorhus** [comment]
@matijs Did you intend to push additional commits?

**Comment by matijs** [comment]
@sindresorhus yep, only fiddled with a test and opened a PR.

**Comment by sindresorhus** [comment]
Any chance you would be able to finish this up? Or should I close?

**Comment by sindresorhus** [comment]
Fixed by #110

**Pull request closed without merging**
