### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by fisker**
@sindresorhus What do you think?

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is a good idea. Now we can easily make all rules test against both the ESLint parser, Babel-Eslint, and TypeScript-ESLint.

**Comment by fisker** [comment]
Finally make it work on most rules, some rule can't test with the new logic, ava will throw error on duplicated title, not sure how they are different, will investigate later.

The windows failure should not related.

**Comment by sindresorhus** [comment]
Is this ready?

**Comment by sindresorhus** [comment]
> The windows failure should not related.

What's causing the Windows failures?

**Comment by fisker** [comment]
I don't know why fail on windows, says timeout, but  I don't know how to increase timeout.

**Comment by sindresorhus** [comment]
It's just strange that it fails now and not in master.

**Comment by fisker** [comment]
And it passed on my local windows.

**Comment by fisker** [comment]
I tried again, `npx ava` pass, `yarn test` fails.

**Comment by fisker** [comment]
It seems `npx ava` pass, but `npx nyc ava` fails

**Comment by sindresorhus** [comment]
Maybe just make it `npx nyc ava` => `npx ava` for now until we can figure out the issue?

**Comment by fisker** [comment]
Good to go.

**Comment by sindresorhus** [comment]
Great! 👌

**Pull request merged**
