### PR TITLE
Clarify variable names in `prefer-set-has` rule doc

### PR DESCRIPTION
**Pull request by bmish**

### CODE REVIEW

**Comment by fisker** [comment]
`item` is not a good  name, MDN  use [`valueToFind `](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

**Comment by bmish** [comment]
Good point! Updated.

**Comment by fisker** [comment]
Thanks

**Comment by fisker** [comment]
Thanks

**Pull request merged**
