### PR TITLE
`prefer-set-has`: Use suggestions if node has type annotation

### LINKED ISSUE #1148: prefer-set-has doesn't autofix types
When "autofixing" an array to a set, the type definition should be fixed too (or the fix should be skipped).

prefer-set-has

```ts
const a: Array<'foo' | 'bar'> = ['foo', 'bar']

for (let i = 0; i < 3; i++) {
  if (a.includes(someString)) {
    console.log(123)
  }
}
```

This is corrected to:

```ts
const a: Array<'foo' | 'bar'> = new Set(['foo', 'bar'])

for (let i = 0; i < 3; i++) {
  if (a.has(someString)) {
    console.log(123)
  }
}
```

Which is confusing and wrong.

### PR DESCRIPTION
**Pull request by fisker**
Fixes #1148

### CODE REVIEW

**Comment by sindresorhus** [comment]
Wouldn't it be better to just fix the type?

**Comment by fisker** [comment]
I don't have the knowledge to fix it.  As I understand array could be  `foo[]` or `Array<foo>`?

**Comment by fisker** [comment]
I'll let someone else to fix it then.

**Comment by sindresorhus** [comment]
Ok. I think this PR is a good workaround for now though. Could you reopen? I can just make an issue afterwards for actually fixing the type and someone can pick it up if they want.

**Pull request merged**
