### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by brettz9**
- Linting: Apply linting with rc file (unicorn/recommended and eslint:recommended, with a few tweaks), allowing IDEs to display during development
- Linting Add ignore file (to avoid errors when viewing `node_modules` and to enable checks on default-ignored `.eslintrc.js`)
- Linting (package.json): Add recommended `bugs`, `homepage` and `contributors` (used on npmjs.com)
- Refactoring (package.json): Use URLs to facilitate IDE URL opening (e.g., `cmd-O` in Atom when hovering a URL will open it)

### CODE REVIEW

**Comment by fisker** [comment]
We have `xo` and `yarn lint` script.

**Comment by brettz9** [comment]
Those must be run manually, no? I'm adding this so that my IDE can discover the settings and report errors while I'm developing on the codebase.

**Comment by sindresorhus** [comment]
Thanks for the PR, but this is not something we want.

**Comment by sindresorhus** [comment]
> Linting: Apply linting with rc file (unicorn/recommended and eslint:recommended, with a few tweaks), allowing IDEs to display during development

There are editor plugins for XO: https://github.com/xojs/xo#editor-plugins

> Linting (package.json): Add recommended bugs, homepage and contributors (used on npmjs.com)

These are inferred from the other fields.

**Comment by brettz9** [comment]
Ok, thanks for the info on the editor plugins. As far as the other items being inferred from other fields, besides the reasons I mentioned (allowing IDEs to easily jump from a link), these are used on the site npmjs.com (which does not do any inferring). So if I go to the npmjs.com page, I have to take extra link jumps to get to the bugs page.

**Pull request closed without merging**
