### PR TITLE
Update `prevent-abbreviations` to ignore uppercase letters

### PR DESCRIPTION
**Pull request by fisker**
variable name `ESLint` is reported error, which should not.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> variable name ESLint is reported error, which should not.

Why should it not?

**Comment by fisker** [comment]
the logic in master is split letters until uppercase one, so `ESLint` will split into  `E`, `S` and `Lint`, `E` has replacement so will report rename to  `ErrorSLint` or  `EventSLint`, which is ridiculous.

also  `isJPEG` is suggest `isJPErrorG` or ``isJPEventG` `

**Comment by sindresorhus** [comment]
Ok. Makes sense. Can you add some more tests?

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by fisker** [comment]
done

**Comment by sindresorhus** [comment]
@fisker You have done a lot of great PRs here, would you be interested in joining the project as a maintainer? No worries if not :)

**Comment by fisker** [comment]
@sindresorhus I'd be honored to be a maintainer of this great project, thanks.

**Comment by sindresorhus** [comment]
@fisker Awesome :) We usually prefer to do PRs for most things as it's always good to get another set of eyes looking at changes.

**Comment by sindresorhus** [comment]
What I need to most help with is reviewing other PRs. I also need opinions on rule proposals and other issues.

**Pull request merged**
