### PR TITLE
Remove `eslint-template-visitor` dependency

### PR DESCRIPTION
**Pull request by fisker**
I understand that @futpib made this package specially for this repo, and I don't want to hurt futpib's feelings.

The reason behind this refactor,

1. This package includes babel parser, so [it's quite big(~1.5mb)](https://arve0.github.io/npm-download-size/#eslint-plugin-unicorn)
1. These places seem not too complicated after rewrite

### CODE REVIEW

**Review by futpib — APPROVED** [review]

**Comment by fisker** [comment]
Thanks for the approval.

**Comment by sindresorhus** [comment]
You should remove it from package.json too.

**Comment by fisker** [comment]
I remember I did... must forgot to commit.

**Comment by sindresorhus** [comment]
Can you also fix the merge conflict?

**Pull request merged**
