### PR TITLE
Fix no-fn-reference-in-iterator to support static Promise methods

### LINKED ISSUE #124: `no-fn-reference-in-iterator` rule should not apply to `Promise` static methods
Bluebird adds [`Promise.map()`](http://bluebirdjs.com/docs/api/promise.map.html) which has a different semantic. Since Bluebird is a very popular module, we should add an exclusion for it. So any static method on `Promise` should be ignored.

### PR DESCRIPTION
**Pull request by SamVerschueren**
This PR fixes #124.

### CODE REVIEW

**Comment by sindresorhus** [comment]
That was fast :)

**Comment by SamVerschueren** [comment]
Hehe :tada: :)

**Comment by eaviles** [comment]
What about [Promise.filter](http://bluebirdjs.com/docs/api/promise.filter.html)? Or the other Bluebird-specific Promise.x?

**Comment by sindresorhus** [comment]
@eaviles As you can see in the code it ignores anything on the `Promise` object, including `.filter`.

**Pull request merged**
