### PR TITLE
`explicit-length-check`: Support Vue SFC files

### PR DESCRIPTION
**Pull request by fisker**
Can we accept this?

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sure!

**Comment by fisker** [comment]
Do you think we should make all rule work for Vue SFC? We can add one line [here](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/91996110a45ecb35c0c14f98dae90d88b904e863/rules/utils/load-rule.js#L34).

**Comment by fisker** [comment]
Let's start with some other rules first, I'll send more PRs

**Comment by sindresorhus** [comment]
> Do you think we should make all rule work for Vue SFC?

I don't mind. Vue is quite popular, so it's gonna help a lot of people.

**Comment by fisker** [comment]
I'm worried about auto-fix for some rule, for example `prefer-string-replace-all`, we'll fix `<div v-if='foo.replace(/a/g, "")'` to `<div v-if='foo.replaceAll('a', "")'`, but we can't use single quote for the fix, it's in single quoted attribute, so let's start with some safe rules first.

**Pull request merged**
