### PR TITLE
Fix cases without space after keywords

### PR DESCRIPTION
**Pull request by fisker**
JS allows no space after keywords in some cases, this PR fixes them.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> this PR fixes them.

What exactly does it fix? From my understanding, you're adding support for code where there's no space after a keyword, correct? That's quite an edge-case, and shouldn't that be the responsibility of the JS parser? I might be misunderstanding this though.

**Comment by fisker** [comment]
```js
const[,,thirdElement] = foo;
```

Without this PR(incorrect),

```js
constthirdElement = foo[2];
```


Now

```js
const thirdElement = foo[2];
```

**Comment by sindresorhus** [comment]
But what is the reason we need special handling for it? It seems like something the JS parser and ESLint should handle.

**Comment by fisker** [comment]
No, they parse the original code correctly, it's valid code, engine can run it.

**Comment by sindresorhus** [comment]
I feel like `fixer.replaceText` should do what `fixSpaceAroundKeyword` does built-in. Maybe you could open an ESLint issue about that.

**Pull request merged**
