### PR TITLE
`prefer-number-properties`: Test suggestions output

### PR DESCRIPTION
**Pull request by fisker**
Didn't know this can be tested.

https://eslint.org/docs/developer-guide/nodejs-api#testing-suggestions

### CODE REVIEW

**Comment by fisker** [comment]
I wonder is there a way to apply suggestions fix via CLI, so we can test in integration-test.

**Comment by sindresorhus** [comment]
> I wonder is there a way to apply suggestions fix via CLI, so we can test in integration-test.

Maybe worth opening an ESLint issue about that?

**Comment by fisker** [comment]
Let me check how vscode-eslint works first.

**Comment by fisker** [comment]
Opened an issue, https://github.com/eslint/eslint/issues/13103

**Pull request merged**
