### PR TITLE
Enable `prettier` on codebase

### PR DESCRIPTION
**Pull request by fisker**
Prettier sometimes makes codes more readable.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'm not a big fan of Prettier. It does make some code look nicer, but very often it also makes weird choices that makes the code worse. It is just too focused on keeping the line width. I also have a special dislike for it as I waste so much time on PRs where people run Prettier on my code and I have to tell them to undo it.

**Comment by fisker** [comment]
I'm fine with your choice

**Comment by sindresorhus** [comment]
I ran Prettier locally and cherry-picked the changes I agree with: https://github.com/sindresorhus/eslint-plugin-unicorn/commit/8fd4ddac77558b37520886217b5c0fa17af182d2

**Comment by fisker** [comment]
Thanks, looks good.

**Pull request closed without merging**
