### PR TITLE
`expiring-todo-comments`: Fix compatibility with ESLint 9.15

### LINKED ISSUE #2496: `expiring-todo-comments` Broken in ESlint `9.15.0`
`unicorn/expiring-todo-comments` Broken in ESlint `9.15.0`. Works fine in `9.14.0`.

> TypeError: Error while loading rule 'unicorn/expiring-todo-comments': Cannot read properties of undefined (reading 'decoration')

The above error occurs when reading a file that has the following comment:

```js
// Note: If none of the slotted options are selected, select all
```

Relevant portion of ESLint config is:

```js
{
  files: ['**/*'],
  extends: [eslint.configs.recommended, unicorn.configs['flat/recommended']],
  linterOptions: {
    reportUnusedDisableDirectives: true,
  },
},
```

### PR DESCRIPTION
**Pull request by marcalexiei**
Close #2496.

I added the default options to `expiring-todo-comments` rule to avoid error when running this config with `eslint@9.15`.

I also added `Iterator` to `languageOptions.globals` otherwise the recommended config test will fail.

I tested that the patch works also with `eslint@9.14` but let me know if want that I try to test  multiple version of `ESLint` in `CI` workflow

---

> [!WARNING]
> I cloned and checkout `main` branch then I installed the dependencies using  `npm i`.
> After that I ran `npm run lint` I got
> ```text
> 27 warnings
> 56 errors
> ```
> is this expected or I have missed some step during setup?

### CODE REVIEW

**Comment by marcalexiei** [comment]
@sindresorhus I see you opened #2498, this PR is related to that `eslint` change.
If you have some insight about how to fix CI it would be great (I would consider add `package-lock.json` to git and fix the issues in a different PR).

**Comment by ipanasenko** [comment]
Would love to see this merged, this prevents us from bumping eslint

**Review by fisker — APPROVED** [review]

**Comment by voxpelli** [comment]
Added a PR to fix this in upstream as well: https://github.com/eslint/eslint/pull/19166 To avoid failures for those using unicorn <15.x

I guess backporting of this PR to 14.x is not something that you would be interested in?

**Comment by voxpelli** [comment]
That issue was closed referencing https://github.com/eslint/eslint/issues/19169 that will document that extension of built in rules are discouraged, they should be forked instead.

**Pull request merged**
