### PR TITLE
Add `callOrNewExpressionSelector`

### PR DESCRIPTION
**Pull request by fisker**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Since we're making reusable tools, wouldn't it be easier to work with the AST directly in these tools rather than generate strings for the query syntax?

**Comment by fisker** [comment]
Here is why I prefer use selector,

selector

```js
'[a.b.c="foo"]'
```

js code

```js
if (a && a.b && a.b.c === 'foo');
```

waiting for this support

```js
if (a?.b?.c === 'foo'):
```

**Comment by sindresorhus** [comment]
Yeah, I agree. So I think we should use the AST more when we can use `?` (Node.js 14). It's much easier to make typo mistakes with string construction.

**Comment by fisker** [comment]
Yes, we should use more ast by that time.

There is also a trouble when use selector, it's hard to select `MemberExpression` and `CallExpression` in 
 optional chain, because `ChainExpression` can be any level, makes the selector very difficult to match, if use js code, we can easily skip it. Just let you know.

**Comment by fisker** [comment]
I hate that AST design.

**Pull request merged**
